
@startuml MVA_MGM_Architecture

class "Model"  << (M,#FF7700) >> {
}

class "Mediators (adapter/controller)" << (C,#FF7700) >> {
    model reference
    dom reference
    notify()
}

class "View (GUI/DOM)" << (V,#FF7700) >> {
    buttons
    text inputs
    checkbox inputs
}

class App {
    model reference
}

"Mediators (adapter/controller)" --> "View (GUI/DOM)" : set DOM
"View (GUI/DOM)" ..> "Mediators (adapter/controller)" : GUI events
"View (GUI/DOM)" ..> App : GUI events
Model ..> "Mediators (adapter/controller)" : setter events (notify)
App --> Model : set model
@enduml

